"""fix_model_relationships_batch

Revision ID: 20e7b2359937
Revises: ce22c9bb631f
Create Date: 2026-08-05 17:59:10.985583

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7b2359937'
down_revision = 'ce22c9bb631f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # inventory_movements - add foreign key to products
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_inventory_movements_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # journal_lines - add foreign key to accounts with RESTRICT
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_journal_lines_account_id_accounts'), 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')

    # payments - add foreign key to bank_accounts
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_payments_bank_account_id_bank_accounts'), 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')

    # purchase_invoices - add foreign keys
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_purchase_invoices_created_by_users'), 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_invoices_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_invoices_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')

    # purchase_items - add foreign key to products
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_purchase_items_product_id_products'), 'products', ['product_id'], ['id'], ondelete='SET NULL')

    # sale_invoices - add foreign keys
    with op.batch_alter_table('sale_invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sale_invoices_customer_id_customers'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sale_invoices_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sale_invoices_created_by_users'), 'users', ['created_by'], ['id'])

    # sale_items - add foreign key to products
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sale_items_product_id_products'), 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # sale_items - drop foreign key
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_items_product_id_products'), type_='foreignkey')

    # sale_invoices - drop foreign keys
    with op.batch_alter_table('sale_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_invoices_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sale_invoices_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sale_invoices_customer_id_customers'), type_='foreignkey')

    # purchase_items - drop foreign key
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_items_product_id_products'), type_='foreignkey')

    # purchase_invoices - drop foreign keys
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_invoices_supplier_id_suppliers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_invoices_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_invoices_created_by_users'), type_='foreignkey')

    # payments - drop foreign key
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_bank_account_id_bank_accounts'), type_='foreignkey')

    # journal_lines - drop foreign key
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_lines_account_id_accounts'), type_='foreignkey')

    # inventory_movements - drop foreign key
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_movements_product_id_products'), type_='foreignkey')
    # ### end Alembic commands ###
