"""phase2_transaction_core

Revision ID: ce22c9bb631f
Revises: cee0fa5c4c7d
Create Date: 2026-06-30 23:31:50.385913
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ce22c9bb631f'
down_revision: str | None = 'cee0fa5c4c7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_account_type'), 'bank_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_bank_accounts_active'), 'bank_accounts', ['active'], unique=False)
    op.create_index(op.f('ix_bank_accounts_deleted_at'), 'bank_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_name'), 'bank_accounts', ['name'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_table('invoice_counters',
    sa.Column('series', sa.String(length=20), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('series')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['date'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_bank_account_id'), 'payments', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_payments_date'), 'payments', ['date'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_payments_reference_type'), 'payments', ['reference_type'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoices_date'), 'purchase_invoices', ['date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_id'), 'purchase_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_number'), 'purchase_invoices', ['number'], unique=True)
    op.create_index(op.f('ix_purchase_invoices_payment_status'), 'purchase_invoices', ['payment_status'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_supplier_id'), 'purchase_invoices', ['supplier_id'], unique=False)
    op.create_table('sale_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_invoices_customer_id'), 'sale_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_date'), 'sale_invoices', ['date'], unique=False)
    op.create_index(op.f('ix_sale_invoices_id'), 'sale_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_number'), 'sale_invoices', ['number'], unique=True)
    op.create_index(op.f('ix_sale_invoices_payment_status'), 'sale_invoices', ['payment_status'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_id'), 'journal_lines', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_items_product_id'), 'purchase_items', ['product_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_purchase_items_product_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_journal_lines_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_sale_invoices_payment_status'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_number'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_id'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_date'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_customer_id'), table_name='sale_invoices')
    op.drop_table('sale_invoices')
    op.drop_index(op.f('ix_purchase_invoices_supplier_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_payment_status'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_number'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_date'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_payments_reference_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_bank_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('invoice_counters')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_bank_accounts_name'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_deleted_at'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_active'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_type'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

